In [1]:
pip install ipykernel pandas pyarrow

Requirement already satisfied: ipykernel in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (7.2.0)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting pyarrow
  Downloading pyarrow-24.0.0-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: comm>=0.1.1 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (9.13.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (26.2)
Requirement already satisfied: psutil>=5.7 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipykernel) (5.14.3)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: colorama>=0.4.4 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.6)
Requirement already satisfied: six>=1.5 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: wcwidth in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\fernandacorrea\documents\documentos belén\prueba ds\prueba-tecnica-ds-propiedata\notebooks\.venv\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ------------- -------------------------- 3.4/9.7 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 27.4 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 20.2 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp312-cp312-win_amd64.whl (27.4 MB)
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   --------- ------------------------------ 6.8/27.4 MB 32.1 MB/s eta 0:00:01
   -------------------- ------------------- 13.9/27.4 MB 34.9 MB/s eta 0:00:01
   ---------------------------- ----------- 19.4/27.4 MB 31.4 MB/s eta 0:00:01
   -------------------------------------- - 26.2/27.4 MB 31.3 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.4 MB 31.4 MB/s eta 0:00:01
   ---------------------------------------- 27.4/27.4 MB 22.2 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------- ----------------- 6.8/12.3 MB 34.9 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 32.8 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 23.4 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pyarrow, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2 pyarrow-24.0.0 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

a = pd.read_csv("../data/listings_plataforma_A.csv")
b = pd.read_csv("../data/listings_plataforma_B.csv")
c = pd.read_csv("../data/listings_plataforma_C.csv")

print("Los archivos se cargaron correctamente.")

Los archivos se cargaron correctamente.

In [ ]:
a.head()

,id_aviso,titulo,zona_barrio,tipo,precio,expensas,superficie_total,superficie_cubierta,ambientes,dormitorios,banios,antiguedad,cochera,balcon,amenities,latitud,longitud,fecha_publicacion
0,A-700480,Departamento en alquiler en Belgrano - 4 ambie...,BELGRANO,Departamento,1.267.000,140298.0,75,75.0,4 amb.,3.0,2.0,4 años,Sí,Sí,NaN,-34.549646421652646,-58.462834001141694,04/01/2025
1,A-220016,Departamento en alquiler en Almagro - 2 ambientes,Almagro,Departamento,584.000,77822.0,39,NaN,2 amb.,1.0,NaN,6,No,No,NaN,-34.60873815826056,-58.43909947532191,15/01/2024
2,A-492142,Departamento en alquiler en Flores - 2 ambientes,Flores,Departamento,252.000,NaN,35 m²,35.0,2,NaN,1.0,23,Sí,No,NaN,"-34,62205081312381",-58.45626733855754,07/03/2024
3,A-675147,PH en alquiler en Belgrano - 2 ambientes,Belgrano,PH,546.000,NaN,38 m²,38.0,2 amb.,1.0,1.0,A estrenar,No,No,Pileta,-34.574756771995716,-58.463757544997684,04/12/2024
4,A-307536,Departamento en alquiler en Villa Urquiza - 1 ...,Villa Urquiza,Departamento,337.000,52942.0,33 m²,NaN,1,NaN,1.0,2,No,Sí,NaN,-34.55428879305003,-58.4866156408398,25/02/2024

In [6]:
a.info()

<class 'pandas.DataFrame'>
RangeIndex: 3662 entries, 0 to 3661
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_aviso             3662 non-null   str
 1   titulo               3662 non-null   str
 2   zona_barrio          3662 non-null   str
 3   tipo                 3662 non-null   str
 4   precio               3662 non-null   str
 5   expensas             1990 non-null   float64
 6   superficie_total     3662 non-null   str
 7   superficie_cubierta  3152 non-null   float64
 8   ambientes            3662 non-null   str
 9   dormitorios          3298 non-null   float64
 10  banios               3383 non-null   float64
 11  antiguedad           3342 non-null   str
 12  cochera              3662 non-null   str
 13  balcon               3662 non-null   str
 14  amenities            336 non-null    str
 15  latitud              3662 non-null   str
 16  longitud             3662 non-null   str
 17  fecha_publicacion    3662 non-null   str
dtypes: float64(4), str(14)
memory usage: 1.0 MB

In [11]:
print("Tipos en A:", a['tipo'].unique())

Tipos en A: <ArrowStringArray>
['Departamento', 'PH', 'Casa']
Length: 3, dtype: str

In [12]:
print("Tipos en A:", a['superficie_total'].unique())

Tipos en A: <ArrowStringArray>
[    '75',     '39',  '35 m²',  '38 m²',  '33 m²',     '76',  '66 m²',
  '37 m²',     '60', '102 m²',
 ...
 '143 m²', '152 m²', '156 m²',    '203', '178 m²',    '150', '188 m²',
    '162',    '117',    '149']
Length: 284, dtype: str

In [13]:
print("Tipos en A:", a['ambientes'].unique())

Tipos en A: <ArrowStringArray>
['4 amb.', '2 amb.',      '2',      '1',      '3', '3 amb.', '6 amb.',
 '1 amb.',      '4',      '5',      '6', '5 amb.',      '7', '7 amb.',
      '8', '8 amb.']
Length: 16, dtype: str

In [14]:
print("Tipos en A:", a['antiguedad'].unique())

Tipos en A: <ArrowStringArray>
[    '4 años',          '6',         '23', 'A estrenar',          '2',
         '24',         '16',          '5',         '13',         '37',
 ...
    '73 años',    '55 años',    '46 años',    '71 años',    '57 años',
    '37 años',         '58',         '66',    '59 años',    '72 años']
Length: 132, dtype: str

In [15]:
print("Tipos en A:", a['amenities'].unique())

Tipos en A: <ArrowStringArray>
[nan, 'Pileta']
Length: 2, dtype: str

In [7]:
b.head()

,listing_id,category_l1,category_l2,property_type,neighborhood,price_ars,covered_area_m2,total_area_m2,rooms,bedrooms,bathrooms,age_years,has_garage,has_balcony,has_pool,lat,lng,created_at
0,MLA757902287,Inmuebles,Alquiler,DEPARTAMENTO,Palermo,713000.0,50.0,50.0,NaN,2.0,1.0,14.0,False,True,False,-34.549232,-58.425510,2025-01-18 00:00:00
1,MLA371511639,Inmuebles,Alquiler,DEPARTAMENTO,Almagro,724000.0,50.0,50.0,2.0,1.0,1.0,NaN,False,False,False,-34.586467,-58.439921,2024-08-08 00:00:00
2,MLA154908801,Inmuebles,Alquiler,DEPARTAMENTO,Almagro,348000.0,42.0,NaN,2.0,NaN,1.0,13.0,True,False,False,-34.607493,-58.417589,2024-08-18 00:00:00
3,MLA403100436,Inmuebles,Alquiler,DEPARTAMENTO,Villa Urquiza,1217000.0,66.0,66.0,2.0,1.0,1.0,2.0,True,True,False,-34.567514,-58.487023,2024-11-03 00:00:00
4,MLA346000441,Inmuebles,Alquiler,CASA,Palermo,1121000.0,86.0,164.0,3.0,2.0,1.0,1.0,True,False,True,-34.589963,-58.444575,2025-03-22 00:00:00

In [8]:
b.info()

<class 'pandas.DataFrame'>
RangeIndex: 3639 entries, 0 to 3638
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   listing_id       3639 non-null   str
 1   category_l1      3639 non-null   str
 2   category_l2      3639 non-null   str
 3   property_type    3639 non-null   str
 4   neighborhood     3639 non-null   str
 5   price_ars        3426 non-null   float64
 6   covered_area_m2  3452 non-null   float64
 7   total_area_m2    2939 non-null   float64
 8   rooms            3501 non-null   float64
 9   bedrooms         3523 non-null   float64
 10  bathrooms        3497 non-null   float64
 11  age_years        2568 non-null   float64
 12  has_garage       3639 non-null   bool
 13  has_balcony      3639 non-null   bool
 14  has_pool         3639 non-null   bool
 15  lat              3639 non-null   float64
 16  lng              3639 non-null   float64
 17  created_at       3639 non-null   str
dtypes: bool(3), float64(9), str(6)
memory usage: 672.9 KB

In [9]:
c.head()

,codigo,operacion,tipo_inmueble,barrio,precio_publicado,superficie,descripcion,coordenadas,publicado
0,AP-64391,Alquiler,ph,Villa Urquiza,$678.000/mes,55,2 ambientes. 1 dorm. 1 baños. pileta,"-34.57599599633878,-58.47863988110282",10-03-2024
1,AP-82260,Alquiler,ph,Colegiales,$700.000/mes,50,2 ambientes. 1 dorm. 1 baños. balcón. 11 años,"-34.582690398643514,-58.4524965859866",30-11-2024
2,AP-66765,Alquiler,departamento,Caballito,$719.000/mes,41,3 ambientes. 2 baños. 11 años,NaN,28-07-2024
3,AP-42570,Alquiler,departamento,Villa Crespo,$1.391.000/mes,58,3 ambientes. 2 dorm. con cochera. 4 años,NaN,31-12-2024
4,AP-64652,Alquiler,departamento,Recoleta,Consultar,53,3 ambientes. 2 dorm. 2 baños. con cochera. 18 ...,NaN,08-01-2025

In [10]:
c.info()

<class 'pandas.DataFrame'>
RangeIndex: 3699 entries, 0 to 3698
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   codigo            3699 non-null   str
 1   operacion         3699 non-null   str
 2   tipo_inmueble     3699 non-null   str
 3   barrio            3699 non-null   str
 4   precio_publicado  3699 non-null   str
 5   superficie        3513 non-null   str
 6   descripcion       3682 non-null   str
 7   coordenadas       2235 non-null   str
 8   publicado         3699 non-null   str
dtypes: str(9)
memory usage: 676.2 KB